version: 0.2
phases:
  install:
    commands:
      - cd 01api
      - aws cloudformation package --template-file sample-api.yaml
                                   --s3-bucket <REPLACE_ME_WITH_UNIQUE_BUCKET_NAME>
                                   --s3-prefix api-code
                                   --output-template-file sample-api-output.yaml
artifacts:
  type: zip
  files:
    - 01api/sample-api-output.yaml
